"""
Blade website backend.

Serves the command documentation (generated by command_export.py from
the bot's own command_meta registry), the variable reference, and a
live status endpoint fed by the bot process via data/status.json.

Run:
    python website/backend/command_export.py   # regenerate commands.json after any command change
    uvicorn website.backend.main:app --reload --port 8000
"""

from __future__ import annotations

import json
import os
import time

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

BASE_DIR = os.path.dirname(__file__)
COMMANDS_PATH = os.path.join(BASE_DIR, "data", "commands.json")
BOT_STATUS_PATH = os.path.join(BASE_DIR, "data", "status.json")

app = FastAPI(title="Blade API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # tighten to your actual frontend origin in production
    allow_methods=["GET"],
    allow_headers=["*"],
)

# --- Variable reference (mirrors core/variables.py - update both together) ---
VARIABLES = {
    "Guild": [
        {"name": "{guild.name}", "description": "Server name", "example": "Blade Community"},
        {"name": "{guild.id}", "description": "Server ID", "example": "123456789012345678"},
        {"name": "{guild.count}", "description": "Member count", "example": "1,204"},
        {"name": "{guild.owner_id}", "description": "Server owner's user ID", "example": "234567890123456789"},
    ],
    "User": [
        {"name": "{user.name}", "description": "Username", "example": "alex"},
        {"name": "{user.id}", "description": "User ID", "example": "345678901234567890"},
        {"name": "{user.mention}", "description": "Pings the user", "example": "@alex"},
        {"name": "{user.avatar}", "description": "Avatar URL", "example": "https://cdn.discordapp.com/..."},
    ],
    "Channel": [
        {"name": "{channel.name}", "description": "Channel name", "example": "general"},
        {"name": "{channel.id}", "description": "Channel ID", "example": "456789012345678901"},
    ],
    "Leveling": [
        {"name": "{level}", "description": "The member's new level", "example": "12"},
        {"name": "{xp}", "description": "The member's total XP", "example": "4,820"},
    ],
    "Date/Time": [
        {"name": "{date}", "description": "Current UTC date", "example": "2026-08-18"},
        {"name": "{time}", "description": "Current UTC time", "example": "14:03:00"},
    ],
}


def _load_commands() -> list[dict]:
    if not os.path.exists(COMMANDS_PATH):
        return []
    with open(COMMANDS_PATH, encoding="utf-8") as f:
        return json.load(f)


@app.get("/api/commands")
def list_commands(category: str | None = None):
    commands_ = _load_commands()
    if category:
        commands_ = [c for c in commands_ if c["category"].lower() == category.lower()]
    return {"commands": commands_}


@app.get("/api/commands/search")
def search_commands(q: str):
    q_lower = q.lower().strip()
    if not q_lower:
        return {"commands": []}
    commands_ = _load_commands()
    results = [
        c for c in commands_
        if q_lower in c["name"].lower()
        or q_lower in c["description"].lower()
        or any(q_lower in a.lower() for a in c.get("aliases", []))
    ]
    return {"commands": results}


@app.get("/api/commands/{name}")
def get_command(name: str):
    commands_ = _load_commands()
    for c in commands_:
        if c["name"].lower() == name.lower() or name.lower() in [a.lower() for a in c.get("aliases", [])]:
            return c
    raise HTTPException(status_code=404, detail="Command not found")


@app.get("/api/categories")
def list_categories():
    commands_ = _load_commands()
    categories: dict[str, int] = {}
    for c in commands_:
        categories[c["category"]] = categories.get(c["category"], 0) + 1
    return {"categories": [{"name": k, "command_count": v} for k, v in sorted(categories.items())]}


@app.get("/api/variables")
def list_variables():
    return {"groups": VARIABLES}


@app.get("/api/status")
def status():
    if not os.path.exists(BOT_STATUS_PATH):
        return {"online": False, "reason": "Bot has not reported status yet."}

    with open(BOT_STATUS_PATH, encoding="utf-8") as f:
        data = json.load(f)

    # If the bot hasn't updated status in >3 minutes, treat it as offline
    # rather than showing stale numbers as if they were live.
    if time.time() - data.get("updated_at", 0) > 180:
        return {"online": False, "reason": "Status data is stale."}

    return data


if __name__ == "__main__":
    # Lets platforms like Render/Railway run this file directly with `python main.py`
    # instead of requiring a separate uvicorn command. They inject the port via $PORT.
    import uvicorn

    port = int(os.environ.get("PORT", 8000))
    uvicorn.run(app, host="0.0.0.0", port=port)
